# Macro file for the initialization of project1
# in interactive session
#
# Set some default verbose
/control/verbose 2
/control/saveHistory
/run/verbose 2
#
# Change the default number of threads (in multi-threaded mode)
#/run/numberOfThreads 4
#
# Initialize kernel
/run/initialize
#
# Visualization setting
/control/execute vis.mac

/event/verbose 0
/tracking/verbose 1

/analysis/openFile Project1
/analysis/write
/analysis/closeFile isReset
